spring:
  datasource:
    name: test #test #数据库名
    url:  jdbc:mysql://localhost:3306/test #url
    username: root #用户名
    password: root1234 #密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库链接驱动


mybatis:
  mapper-locations: classpath:mapper/*.xml #配置映射文件
  type-aliases-package: upc.csp1_0.model #配置实体类

server:
  port: 9000
#端口号


